INSERT INTO USERS (ID, USERNAME, EMAIL, BIRTH_DATE) VALUES(1, 'Jaime Rojas', 'jaimitorojas@gmail.com', '1987-04-11');-- 1
INSERT INTO USERS (ID, USERNAME, EMAIL, BIRTH_DATE) VALUES(2, 'Julian Oro Duro', 'orodurojulian@gmail.com', '1965-08-21');-- 2

INSERT INTO BLOGS (ID, SUBJECT, AUTHOR_ID) VALUES(1, 'Dragon Ball Blog', 1);-- 1
INSERT INTO BLOGS (ID, SUBJECT, AUTHOR_ID) VALUES(2, 'Blog SUPER Aburrido', 1);-- 2
INSERT INTO BLOGS (ID, SUBJECT, AUTHOR_ID) VALUES(3, 'tOWN sQARE', 1);-- 3
INSERT INTO BLOGS (ID, SUBJECT, AUTHOR_ID) VALUES(4, 'BLOG BLOG y mas BLOG', 2);-- 4


